# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# title: Your awesome title
# email: your-email@domain.com
# description: > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
# github_username:  jekyll

title: Jezrael Arciaga
email: jezarciaga@gmail.com
description: > 
  Hi! My name is Jezrael Arciaga. This blog is for technical stuffs like Emacs, Python, Lisp, Data Science, Linux, and many more. 
baseurl: ""
url: "http://jezifm.github.io"
repository: jezifm/jezifm.github.io
author:
  twitter: jezarciaga

twitter_username: jezarciaga
twitter:
  username: jezarciaga

github_username: jezifm

social:
  name: Jezrael Arciaga
  links:
    - https://twitter.com/jezarciaga
    - https://www.linkedin.com/in/jezrael-arciaga-4785a133
    - https://github.com/jezifm
    - https://www.kaggle.com/jezifm

# Build settings
markdown: kramdown
gems:
  - jekyll-seo-tag
  - jekyll-sitemap
